import type { LenormandCard } from './models';

/** The 36-card Petit Lenormand deck, in standard traditional order. Card #25 (Ring) is the pivot for the yes/no reading. */
export const LENORMAND_CARDS: readonly LenormandCard[] = [
  {
    number: 1,
    name: 'Rider',
    slug: 'rider',
    playingCard: '9♥',
    meaning: 'News, a visitor, something on the way. A message that does not sit still.',
  },
  {
    number: 2,
    name: 'Clover',
    slug: 'clover',
    playingCard: '6♦',
    meaning: 'A small luck. A lucky break that does not last long, but it is real.',
  },
  {
    number: 3,
    name: 'Ship',
    slug: 'ship',
    playingCard: '10♠',
    meaning: 'Travel, trade, something from afar. A departure, or commerce over water.',
  },
  {
    number: 4,
    name: 'House',
    slug: 'house',
    playingCard: 'Q♥',
    meaning: 'Home, family, the roof you keep. Safety, and the place you return to.',
  },
  {
    number: 5,
    name: 'Tree',
    slug: 'tree',
    playingCard: '7♣',
    meaning: 'Health, roots, slow growth. Time, and what is meant to last.',
  },
  {
    number: 6,
    name: 'Clouds',
    slug: 'clouds',
    playingCard: 'Q♣',
    meaning: 'Confusion, doubt, a fog. Wait until it lifts before you decide.',
  },
  {
    number: 7,
    name: 'Snake',
    slug: 'snake',
    playingCard: '9♦',
    meaning: 'A complication, desire, a detour. Someone clever — not always kind.',
  },
  {
    number: 8,
    name: 'Coffin',
    slug: 'coffin',
    playingCard: '10♥',
    meaning: 'An ending. Something is finished, and a space opens after it.',
  },
  {
    number: 9,
    name: 'Bouquet',
    slug: 'bouquet',
    playingCard: '8♦',
    meaning: 'A gift, a compliment, a pleasant surprise. Grace, and a kind word.',
  },
  {
    number: 10,
    name: 'Scythe',
    slug: 'scythe',
    playingCard: 'J♠',
    meaning: 'A sudden cut. Harvest, danger, or a decision that will not wait.',
  },
  {
    number: 11,
    name: 'Whip',
    slug: 'whip',
    playingCard: 'J♦',
    meaning: 'Argument, repetition, hard work. Words that sting, or a sport.',
  },
  {
    number: 12,
    name: 'Bird',
    slug: 'bird',
    playingCard: '7♠',
    meaning: 'Talk, chatter, a short trip. Two voices — or a phone that will not stop.',
  },
  {
    number: 13,
    name: 'Child',
    slug: 'child',
    playingCard: '10♣',
    meaning: 'Something new, small, or naive. Play, a start, a little one.',
  },
  {
    number: 14,
    name: 'Fox',
    slug: 'fox',
    playingCard: '9♠',
    meaning: 'Cunning, a job, watch your back. The clever one at work.',
  },
  {
    number: 15,
    name: 'Bear',
    slug: 'bear',
    playingCard: '10♦',
    meaning: 'Strength, money, a boss. Force that can protect or crush.',
  },
  {
    number: 16,
    name: 'Stars',
    slug: 'stars',
    playingCard: '6♠',
    meaning: 'Hope, guidance, a clear night. The way you wish it would go.',
  },
  {
    number: 17,
    name: 'Stork',
    slug: 'stork',
    playingCard: 'Q♦',
    meaning: 'Change, a move, a birth. Something lands in a new nest.',
  },
  {
    number: 18,
    name: 'Dog',
    slug: 'dog',
    playingCard: '8♠',
    meaning: 'A friend, loyalty, a companion. Someone who stays.',
  },
  {
    number: 19,
    name: 'Tower',
    slug: 'tower',
    playingCard: 'K♣',
    meaning: 'Authority, an institution, distance. Official walls, and a long view.',
  },
  {
    number: 20,
    name: 'Garden',
    slug: 'garden',
    playingCard: '8♥',
    meaning: 'The public, a gathering, the world outside. People, a park, a party.',
  },
  {
    number: 21,
    name: 'Mountain',
    slug: 'mountain',
    playingCard: 'K♠',
    meaning: 'A block, a delay, a long way around. Patience — or a rival in the way.',
  },
  {
    number: 22,
    name: 'Path',
    slug: 'path',
    playingCard: '7♦',
    meaning: 'A choice. Two ways, and you have to pick one.',
  },
  {
    number: 23,
    name: 'Mice',
    slug: 'mice',
    playingCard: '7♥',
    meaning: 'Loss, worry, something nibbling away. Stress, theft, a slow decay.',
  },
  {
    number: 24,
    name: 'Heart',
    slug: 'heart',
    playingCard: 'A♥',
    meaning: 'Love, affection, what you care for. The feeling itself.',
  },
  {
    number: 25,
    name: 'Ring',
    slug: 'ring',
    playingCard: 'A♣',
    meaning: 'A promise, a contract, a bond. In this yes-or-no, it is the card that says yes.',
  },
  {
    number: 26,
    name: 'Book',
    slug: 'book',
    playingCard: 'A♦',
    meaning: 'A secret, a lesson, something not yet opened. Study — or a hidden fact.',
  },
  {
    number: 27,
    name: 'Letter',
    slug: 'letter',
    playingCard: '8♣',
    meaning: 'News on paper. A note, a document, a message at the door.',
  },
  {
    number: 28,
    name: 'Gentleman',
    slug: 'gentleman',
    playingCard: 'K♥',
    meaning: 'A man in the story. In the old packs, the querent if he is one.',
  },
  {
    number: 29,
    name: 'Lady',
    slug: 'lady',
    playingCard: 'Q♠',
    meaning: 'A woman in the story. In the old packs, the querent if she is one.',
  },
  {
    number: 30,
    name: 'Lily',
    slug: 'lily',
    playingCard: 'K♦',
    meaning: 'Peace, age, family, winter. Calm — or an older person nearby.',
  },
  {
    number: 31,
    name: 'Sun',
    slug: 'sun',
    playingCard: '9♣',
    meaning: 'Success, warmth, the thing that works. Daylight, and a clear win.',
  },
  {
    number: 32,
    name: 'Moon',
    slug: 'moon',
    playingCard: 'J♣',
    meaning: 'Recognition, cycles, the night side. Work that is seen — or a mood.',
  },
  {
    number: 33,
    name: 'Key',
    slug: 'key',
    playingCard: 'A♠',
    meaning: 'The answer, access, a yes that opens. The important thing, unlocked.',
  },
  {
    number: 34,
    name: 'Fish',
    slug: 'fish',
    playingCard: 'J♥',
    meaning: 'Money, plenty, business in motion. Water, and what flows.',
  },
  {
    number: 35,
    name: 'Anchor',
    slug: 'anchor',
    playingCard: '6♣',
    meaning: 'Work, staying put, a hold. Stability — or being stuck on purpose.',
  },
  {
    number: 36,
    name: 'Cross',
    slug: 'cross',
    playingCard: '6♥',
    meaning: 'A burden, grief, a test. Fate, and what you have to carry.',
  },
];

export const RING_CARD_NUMBER = 25;
export const YES_NO_CUTOFF = 13;
