import type { LenormandCard } from './models';

/** The 36-card Petit Lenormand deck, in standard traditional order. Card #25 (Ring) is the pivot for the yes/no reading. */
export const LENORMAND_CARDS: readonly LenormandCard[] = [
  {
    number: 1,
    name: 'Rider',
    nameFr: 'Cavalier',
    slug: 'rider',
    playingCard: '9♥',
    meaning: 'News, a visitor, something on the way. A message that does not sit still.',
    meaningFr: 'Une nouvelle, un visiteur, quelque chose en chemin. Un message qui ne tient pas en place.',
  },
  {
    number: 2,
    name: 'Clover',
    nameFr: 'Trèfle',
    slug: 'clover',
    playingCard: '6♦',
    meaning: 'A small luck. A lucky break that does not last long, but it is real.',
    meaningFr: 'Une petite chance. Un coup de chance qui ne dure pas, mais qui est bien réel.',
  },
  {
    number: 3,
    name: 'Ship',
    nameFr: 'Bateau',
    slug: 'ship',
    playingCard: '10♠',
    meaning: 'Travel, trade, something from afar. A departure, or commerce over water.',
    meaningFr: 'Voyage, commerce, quelque chose qui vient de loin. Un départ, ou des affaires outre-mer.',
  },
  {
    number: 4,
    name: 'House',
    nameFr: 'Maison',
    slug: 'house',
    playingCard: 'Q♥',
    meaning: 'Home, family, the roof you keep. Safety, and the place you return to.',
    meaningFr: 'Le foyer, la famille, le toit qu’on garde. La sécurité, et l’endroit où l’on revient.',
  },
  {
    number: 5,
    name: 'Tree',
    nameFr: 'Arbre',
    slug: 'tree',
    playingCard: '7♣',
    meaning: 'Health, roots, slow growth. Time, and what is meant to last.',
    meaningFr: 'Santé, racines, croissance lente. Le temps, et ce qui est fait pour durer.',
  },
  {
    number: 6,
    name: 'Clouds',
    nameFr: 'Nuages',
    slug: 'clouds',
    playingCard: 'Q♣',
    meaning: 'Confusion, doubt, a fog. Wait until it lifts before you decide.',
    meaningFr: 'Confusion, doute, un brouillard. Attends qu’il se lève avant de décider.',
  },
  {
    number: 7,
    name: 'Snake',
    nameFr: 'Serpent',
    slug: 'snake',
    playingCard: '9♦',
    meaning: 'A complication, desire, a detour. Someone clever — not always kind.',
    meaningFr: 'Une complication, du désir, un détour. Quelqu’un de malin — pas toujours bienveillant.',
  },
  {
    number: 8,
    name: 'Coffin',
    nameFr: 'Cercueil',
    slug: 'coffin',
    playingCard: '10♥',
    meaning: 'An ending. Something is finished, and a space opens after it.',
    meaningFr: 'Une fin. Quelque chose se termine, et un espace s’ouvre après.',
  },
  {
    number: 9,
    name: 'Bouquet',
    nameFr: 'Bouquet',
    slug: 'bouquet',
    playingCard: '8♦',
    meaning: 'A gift, a compliment, a pleasant surprise. Grace, and a kind word.',
    meaningFr: 'Un cadeau, un compliment, une bonne surprise. De la grâce, et un mot gentil.',
  },
  {
    number: 10,
    name: 'Scythe',
    nameFr: 'Faux',
    slug: 'scythe',
    playingCard: 'J♠',
    meaning: 'A sudden cut. Harvest, danger, or a decision that will not wait.',
    meaningFr: 'Une coupure soudaine. Récolte, danger, ou une décision qui n’attend pas.',
  },
  {
    number: 11,
    name: 'Whip',
    nameFr: 'Fouet',
    slug: 'whip',
    playingCard: 'J♦',
    meaning: 'Argument, repetition, hard work. Words that sting, or a sport.',
    meaningFr: 'Dispute, répétition, dur labeur. Des mots qui piquent, ou un sport.',
  },
  {
    number: 12,
    name: 'Bird',
    nameFr: 'Oiseaux',
    slug: 'bird',
    playingCard: '7♠',
    meaning: 'Talk, chatter, a short trip. Two voices — or a phone that will not stop.',
    meaningFr: 'Bavardage, discussion, un court trajet. Deux voix — ou un téléphone qui n’arrête pas.',
  },
  {
    number: 13,
    name: 'Child',
    nameFr: 'Enfant',
    slug: 'child',
    playingCard: '10♣',
    meaning: 'Something new, small, or naive. Play, a start, a little one.',
    meaningFr: 'Quelque chose de nouveau, petit, ou naïf. Du jeu, un début, un petit.',
  },
  {
    number: 14,
    name: 'Fox',
    nameFr: 'Renard',
    slug: 'fox',
    playingCard: '9♠',
    meaning: 'Cunning, a job, watch your back. The clever one at work.',
    meaningFr: 'Ruse, un travail, méfie-toi. Le malin au boulot.',
  },
  {
    number: 15,
    name: 'Bear',
    nameFr: 'Ours',
    slug: 'bear',
    playingCard: '10♦',
    meaning: 'Strength, money, a boss. Force that can protect or crush.',
    meaningFr: 'Force, argent, un patron. Une force qui protège ou qui écrase.',
  },
  {
    number: 16,
    name: 'Stars',
    nameFr: 'Étoiles',
    slug: 'stars',
    playingCard: '6♠',
    meaning: 'Hope, guidance, a clear night. The way you wish it would go.',
    meaningFr: 'Espoir, guidance, une nuit claire. La façon dont tu voudrais que ça se passe.',
  },
  {
    number: 17,
    name: 'Stork',
    nameFr: 'Cigogne',
    slug: 'stork',
    playingCard: 'Q♦',
    meaning: 'Change, a move, a birth. Something lands in a new nest.',
    meaningFr: 'Changement, déménagement, une naissance. Quelque chose atterrit dans un nouveau nid.',
  },
  {
    number: 18,
    name: 'Dog',
    nameFr: 'Chien',
    slug: 'dog',
    playingCard: '8♠',
    meaning: 'A friend, loyalty, a companion. Someone who stays.',
    meaningFr: 'Un ami, la loyauté, un compagnon. Quelqu’un qui reste.',
  },
  {
    number: 19,
    name: 'Tower',
    nameFr: 'Tour',
    slug: 'tower',
    playingCard: 'K♣',
    meaning: 'Authority, an institution, distance. Official walls, and a long view.',
    meaningFr: 'Autorité, une institution, la distance. Des murs officiels, et une vue lointaine.',
  },
  {
    number: 20,
    name: 'Garden',
    nameFr: 'Jardin',
    slug: 'garden',
    playingCard: '8♥',
    meaning: 'The public, a gathering, the world outside. People, a park, a party.',
    meaningFr: 'Le public, un rassemblement, le monde extérieur. Des gens, un parc, une fête.',
  },
  {
    number: 21,
    name: 'Mountain',
    nameFr: 'Montagne',
    slug: 'mountain',
    playingCard: 'K♠',
    meaning: 'A block, a delay, a long way around. Patience — or a rival in the way.',
    meaningFr: 'Un blocage, un retard, un long détour. De la patience — ou un rival sur le chemin.',
  },
  {
    number: 22,
    name: 'Path',
    nameFr: 'Chemin',
    slug: 'path',
    playingCard: '7♦',
    meaning: 'A choice. Two ways, and you have to pick one.',
    meaningFr: 'Un choix. Deux voies, et il faut en choisir une.',
  },
  {
    number: 23,
    name: 'Mice',
    nameFr: 'Souris',
    slug: 'mice',
    playingCard: '7♥',
    meaning: 'Loss, worry, something nibbling away. Stress, theft, a slow decay.',
    meaningFr: 'Perte, souci, quelque chose qui grignote. Stress, vol, une lente usure.',
  },
  {
    number: 24,
    name: 'Heart',
    nameFr: 'Cœur',
    slug: 'heart',
    playingCard: 'A♥',
    meaning: 'Love, affection, what you care for. The feeling itself.',
    meaningFr: 'Amour, affection, ce qui compte pour toi. Le sentiment lui-même.',
  },
  {
    number: 25,
    name: 'Ring',
    nameFr: 'Anneau',
    slug: 'ring',
    playingCard: 'A♣',
    meaning: 'A promise, a contract, a bond. In this yes-or-no, it is the card that says yes.',
    meaningFr: 'Une promesse, un contrat, un lien. Dans ce oui-ou-non, c’est la carte qui dit oui.',
  },
  {
    number: 26,
    name: 'Book',
    nameFr: 'Livre',
    slug: 'book',
    playingCard: 'A♦',
    meaning: 'A secret, a lesson, something not yet opened. Study — or a hidden fact.',
    meaningFr: 'Un secret, une leçon, quelque chose pas encore ouvert. L’étude — ou un fait caché.',
  },
  {
    number: 27,
    name: 'Letter',
    nameFr: 'Lettre',
    slug: 'letter',
    playingCard: '8♣',
    meaning: 'News on paper. A note, a document, a message at the door.',
    meaningFr: 'Des nouvelles sur papier. Un mot, un document, un message à la porte.',
  },
  {
    number: 28,
    name: 'Gentleman',
    nameFr: 'Monsieur',
    slug: 'gentleman',
    playingCard: 'K♥',
    meaning: 'A man in the story. In the old packs, the querent if he is one.',
    meaningFr: 'Un homme dans l’histoire. Dans les vieux jeux, le consultant, si c’est un homme.',
  },
  {
    number: 29,
    name: 'Lady',
    nameFr: 'Madame',
    slug: 'lady',
    playingCard: 'Q♠',
    meaning: 'A woman in the story. In the old packs, the querent if she is one.',
    meaningFr: 'Une femme dans l’histoire. Dans les vieux jeux, la consultante, si c’est une femme.',
  },
  {
    number: 30,
    name: 'Lily',
    nameFr: 'Lys',
    slug: 'lily',
    playingCard: 'K♦',
    meaning: 'Peace, age, family, winter. Calm — or an older person nearby.',
    meaningFr: 'Paix, âge, famille, hiver. Le calme — ou une personne plus âgée à proximité.',
  },
  {
    number: 31,
    name: 'Sun',
    nameFr: 'Soleil',
    slug: 'sun',
    playingCard: '9♣',
    meaning: 'Success, warmth, the thing that works. Daylight, and a clear win.',
    meaningFr: 'Réussite, chaleur, ce qui marche. La lumière du jour, et une victoire nette.',
  },
  {
    number: 32,
    name: 'Moon',
    nameFr: 'Lune',
    slug: 'moon',
    playingCard: 'J♣',
    meaning: 'Recognition, cycles, the night side. Work that is seen — or a mood.',
    meaningFr: 'Reconnaissance, cycles, le côté nocturne. Un travail qu’on remarque — ou une humeur.',
  },
  {
    number: 33,
    name: 'Key',
    nameFr: 'Clé',
    slug: 'key',
    playingCard: 'A♠',
    meaning: 'The answer, access, a yes that opens. The important thing, unlocked.',
    meaningFr: 'La réponse, l’accès, un oui qui ouvre. La chose importante, enfin débloquée.',
  },
  {
    number: 34,
    name: 'Fish',
    nameFr: 'Poisson',
    slug: 'fish',
    playingCard: 'J♥',
    meaning: 'Money, plenty, business in motion. Water, and what flows.',
    meaningFr: 'Argent, abondance, des affaires en mouvement. L’eau, et ce qui coule.',
  },
  {
    number: 35,
    name: 'Anchor',
    nameFr: 'Ancre',
    slug: 'anchor',
    playingCard: '6♣',
    meaning: 'Work, staying put, a hold. Stability — or being stuck on purpose.',
    meaningFr: 'Le travail, rester en place, une prise. La stabilité — ou être bloqué exprès.',
  },
  {
    number: 36,
    name: 'Cross',
    nameFr: 'Croix',
    slug: 'cross',
    playingCard: '6♥',
    meaning: 'A burden, grief, a test. Fate, and what you have to carry.',
    meaningFr: 'Un fardeau, un deuil, une épreuve. Le destin, et ce qu’il faut porter.',
  },
];

export const RING_CARD_NUMBER = 25;
export const YES_NO_CUTOFF = 13;
